##  using **Pandas** & **Numpy**

In [1]:
# استدعاء المكتبات 
import pandas as pd
import numpy as np

In [3]:
# تحميل البيانات وجعلها فريم 
df = pd.read_csv('retail_store_sales.csv')

In [19]:
# عرض أول 5 صفوف للتأكد من التحميل
df.head()

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,Online,2024-04-08,True
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9.0,261.0,Digital Wallet,Online,2023-07-23,True
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2.0,43.0,Credit Card,Online,2022-10-05,False
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9.0,247.5,Credit Card,Online,2022-05-07,0
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7.0,87.5,Digital Wallet,Online,2022-10-02,False

In [20]:
# عرض أول 20 صف للتأكد من التحميل
df.head(20)

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,Online,2024-04-08,True
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9.0,261.0,Digital Wallet,Online,2023-07-23,True
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2.0,43.0,Credit Card,Online,2022-10-05,False
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9.0,247.5,Credit Card,Online,2022-05-07,0
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7.0,87.5,Digital Wallet,Online,2022-10-02,False
5,TXN_7482416,CUST_09,Patisserie,Unknown,23.0,10.0,200.0,Credit Card,Online,2023-11-30,0
6,TXN_3652209,CUST_07,Food,Item_1_FOOD,5.0,8.0,40.0,Credit Card,In-store,2023-06-10,True
7,TXN_1372952,CUST_21,Furniture,Unknown,33.5,6.0,201.0,Digital Wallet,In-store,2024-04-02,True
8,TXN_9728486,CUST_23,Furniture,Item_16_FUR,27.5,1.0,27.5,Credit Card,In-store,2023-04-26,False
9,TXN_2722661,CUST_25,Butchers,Item_22_BUT,36.5,3.0,109.5,Cash,Online,2024-03-14,False
10,TXN_8776416,CUST_22,Butchers,Item_3_BUT,8.0,9.0,72.0,Cash,In-store,2024-12-14,True
11,TXN_5422631,CUST_09,Milk Products,Unknown,23.0,8.0,52.0,Digital Wallet,In-store,2025-01-12,True
12,TXN_5874772,CUST_23,Food,Item_2_FOOD,6.5,7.0,45.5,Cash,Online,2023-09-09,True
13,TXN_4413070,CUST_14,Patisserie,Item_24_PAT,39.5,6.0,237.0,Digital Wallet,In-store,2022-05-20,False
14,TXN_2490363,CUST_09,Milk Products,Item_16_MILK,27.5,2.0,55.0,Digital Wallet,Online,2022-05-22,0
15,TXN_1809665,CUST_14,Beverages,Unknown,24.5,6.0,147.0,Credit Card,In-store,2022-05-11,0
16,TXN_7563311,CUST_23,Patisserie,Item_17_PAT,29.0,8.0,232.0,Cash,Online,2024-11-16,True
17,TXN_9634894,CUST_15,Milk Products,Unknown,23.0,10.0,275.0,Digital Wallet,Online,2022-04-17,0
18,TXN_4396807,CUST_17,Electric household essentials,Item_13_EHE,23.0,1.0,23.0,Digital Wallet,In-store,2022-02-07,False
19,TXN_4206593,CUST_01,Furniture,Unknown,35.0,6.0,210.0,Digital Wallet,Online,2025-01-13,False

In [22]:
# عرض أخر 10 صف للتأكد من التحميل

df.tail(10)

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
12565,TXN_1712895,CUST_07,Computers and electric accessories,Item_2_CEA,6.5,5.0,32.5,Digital Wallet,In-store,2024-09-06,False
12566,TXN_6298574,CUST_01,Milk Products,Item_1_MILK,5.0,4.0,20.0,Cash,Online,2023-05-09,False
12567,TXN_4890318,CUST_25,Butchers,Item_3_BUT,8.0,5.0,40.0,Credit Card,In-store,2023-03-28,False
12568,TXN_1096134,CUST_06,Food,Item_4_FOOD,9.5,8.0,76.0,Digital Wallet,In-store,2022-06-11,0
12569,TXN_2318174,CUST_18,Patisserie,Item_1_PAT,5.0,9.0,45.0,Digital Wallet,In-store,2024-05-13,False
12570,TXN_9347481,CUST_18,Patisserie,Item_23_PAT,38.0,4.0,152.0,Credit Card,In-store,2023-09-03,0
12571,TXN_4009414,CUST_03,Beverages,Item_2_BEV,6.5,9.0,58.5,Cash,Online,2022-08-12,False
12572,TXN_5306010,CUST_11,Butchers,Item_7_BUT,14.0,10.0,140.0,Cash,Online,2024-08-24,0
12573,TXN_5167298,CUST_04,Furniture,Item_7_FUR,14.0,6.0,84.0,Cash,Online,2023-12-30,True
12574,TXN_2407494,CUST_23,Food,Item_9_FOOD,17.0,3.0,51.0,Cash,Online,2022-08-06,0

In [5]:
# نظرة عامة على أنواع البيانات والأعمدة غير الفارغة
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12575 entries, 0 to 12574
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    12575 non-null  object
 1   Customer ID       12575 non-null  object
 2   Category          12575 non-null  object
 3   Item              11362 non-null  object
 4   Price Per Unit    11966 non-null  float64
 5   Quantity          11971 non-null  float64
 6   Total Spent       11971 non-null  float64
 7   Payment Method    12575 non-null  object
 8   Location          12575 non-null  object
 9   Transaction Date  12575 non-null  object
 10  Discount Applied  8376 non-null   object
dtypes: float64(3), object(8)
memory usage: 1.1+ MB
None

In [28]:
print(df["Price Per Unit"].sum())
print(df["Price Per Unit"].min())
print(df["Price Per Unit"].max())

293603.5
5.0
41.0

In [30]:
df["Transaction Date"]=pd.to_datetime(df["Transaction Date"])

In [31]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12575 entries, 0 to 12574
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    12575 non-null  object
 1   Customer ID       12575 non-null  object
 2   Category          12575 non-null  object
 3   Item              12575 non-null  object
 4   Price Per Unit    12575 non-null  float64
 5   Quantity          12575 non-null  float64
 6   Total Spent       12575 non-null  float64
 7   Payment Method    12575 non-null  object
 8   Location          12575 non-null  object
 9   Transaction Date  12575 non-null  datetime64[ns]
 10  Discount Applied  12575 non-null  object
dtypes: datetime64[ns](1), float64(3), object(7)
memory usage: 1.1+ MB
None

In [34]:
x=df[df["Transaction Date"]>"1/1/2024"]

In [35]:
x.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4436 entries, 0 to 12572
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    4436 non-null   object
 1   Customer ID       4436 non-null   object
 2   Category          4436 non-null   object
 3   Item              4436 non-null   object
 4   Price Per Unit    4436 non-null   float64
 5   Quantity          4436 non-null   float64
 6   Total Spent       4436 non-null   float64
 7   Payment Method    4436 non-null   object
 8   Location          4436 non-null   object
 9   Transaction Date  4436 non-null   datetime64[ns]
 10  Discount Applied  4436 non-null   object
dtypes: datetime64[ns](1), float64(3), object(7)
memory usage: 415.9+ KB

In [29]:
print(df["Total Spent"].sum())
print(df["Total Spent"].min())
print(df["Total Spent"].max())

1637367.0
5.0
410.0

In [36]:
print(x["Total Spent"].sum())
print(x["Total Spent"].min())
print(x["Total Spent"].max())

578206.5
5.0
410.0

In [ ]:
# هي هي معني كدا دي اقل سنه فيها ربح

In [ ]:
# هعرف اقل تكلفه واعلي تكلفه

In [37]:
x.groupby("Category")["Total Spent"].max()

Category
Beverages                             410.0
Butchers                              410.0
Computers and electric accessories    410.0
Electric household essentials         410.0
Food                                  410.0
Furniture                             410.0
Milk Products                         410.0
Patisserie                            395.0
Name: Total Spent, dtype: float64

In [38]:
x.groupby("Category")["Total Spent"].sum().sort_values()

Category
Milk Products                         63055.0
Patisserie                            66725.5
Butchers                              72310.0
Electric household essentials         72387.0
Food                                  73193.5
Furniture                             73916.5
Computers and electric accessories    74483.0
Beverages                             82136.0
Name: Total Spent, dtype: float64

In [42]:
# الحل الصحيح: استخدام أقواس مربعة مزدوجة
x.groupby("Category")[["Total Spent", "Quantity"]].sum().sort_values(by="Total Spent", ascending=False)

                                    Total Spent  Quantity
Category
Beverages                               82136.0    3373.0
Computers and electric accessories      74483.0    3148.0
Furniture                               73916.5    3158.0
Food                                    73193.5    3170.0
Electric household essentials           72387.0    2940.0
Butchers                                72310.0    2834.0
Patisserie                              66725.5    2960.0
Milk Products                           63055.0    2927.0

In [6]:
# ملخص إحصائي للأرقام (Mean, Std, Min, Max, etc.)  ومعرفه ال outlier 
summary = df.describe()
print(summary)

       Price Per Unit      Quantity   Total Spent
count    11966.000000  11971.000000  11971.000000
mean        23.365912      5.536380    129.652577
std         10.743519      2.857883     94.750697
min          5.000000      1.000000      5.000000
25%         14.000000      3.000000     51.000000
50%         23.000000      6.000000    108.500000
75%         33.500000      8.000000    192.000000
max         41.000000     10.000000    410.000000

In [7]:

# ملخص للبيانات النصية (Categorical)
summary_cat = df.describe(include='object')
print(summary_cat)

       Transaction ID Customer ID                       Category        Item  \
count           12575       12575                          12575       11362
unique          12575          25                              8         200
top       TXN_2407494     CUST_05  Electric household essentials  Item_2_BEV
freq                1         544                           1591         126

       Payment Method Location Transaction Date Discount Applied
count           12575    12575            12575             8376
unique              3        2             1114                2
top              Cash   Online       2022-05-30             True
freq             4310     6354               26             4219

# describe(include='object')

-count: عدد القيم غير المفقودة (Non-null entries).

-unique: عدد القيم الفريدة (المختلفة) في العمود.

-top: القيمة الأكثر تكراراً (الـ Mode).

-freq: عدد مرات تكرار القيمة الـ (top).

In [8]:
# معرفة عدد القيم المفقودة في كل عمود
missing_values = df.isnull().sum()
print(missing_values)

Transaction ID         0
Customer ID            0
Category               0
Item                1213
Price Per Unit       609
Quantity             604
Total Spent          604
Payment Method         0
Location               0
Transaction Date       0
Discount Applied    4199
dtype: int64

In [10]:
# 1. تعويض اسم المنتج المفقود بكلمة Unknown
# Item                1213


df['Item'] = df['Item'].fillna('Unknown')

In [11]:
# 2. تعويض القيم العددية (السعر والكمية) بالوسيط Median
# Price Per Unit       609


df['Price Per Unit'] = df['Price Per Unit'].fillna(df['Price Per Unit'].median())
df['Quantity'] = df['Quantity'].fillna(df['Quantity'].median())

In [12]:
# 3. معالجة Total Spent (هندسياً: يفضل إعادة حسابه بدلاً من مجرد التعويض)
# Quantity             604

df['Total Spent'] = df['Total Spent'].fillna(df['Price Per Unit'] * df['Quantity'])

In [13]:
# 4. تعويض الخصم المفقود بـ 0 (لأن عدم وجود قيمة يعني غالباً عدم تطبيق خصم)
# Total Spent          604

df['Discount Applied'] = df['Discount Applied'].fillna(0)

In [14]:

# التأكد من نظافة الداتا تماماً
print("Missing values after cleaning:")
print(df.isnull().sum())

Missing values after cleaning:
Transaction ID      0
Customer ID         0
Category            0
Item                0
Price Per Unit      0
Quantity            0
Total Spent         0
Payment Method      0
Location            0
Transaction Date    0
Discount Applied    0
dtype: int64

In [15]:
# حفظ البيانات النظيفة
df.to_csv('retail_store_sales_cleaned.csv', index=False)

print("Data Cleaning Process Completed Successfully!")

Data Cleaning Process Completed Successfully!